<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<!--    Mobile viewport optimized: j.mp/bplateviewport-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

<!--    CSS site stylization-->
    <link rel="stylesheet" type="text/css" href="CSS/styles.css"/>

<!--    Web font for site-->
    <link href='http://fonts.googleapis.com/css?family=Ledger' rel='stylesheet' type='text/css'>

    <title><?php echo $pageTitle; ?></title></head>

<body>

<h1><?php echo $pageTitle; ?></h1>
<p id="intro">Plant Information Database</p>
<h2><a href="views/html/latest-tree.inc">Trees</a></h2>
<h3><a href="views/html/latest-flower.inc">Flowers</a></h3>

