<!DOCTYPE html>
<html lang="en">

<header>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <!--    Mobile viewport optimized: j.mp/bplateviewport-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <!--    CSS site stylization-->
    <style type="text/css" href="CSS/styles.css">

        body{
            background: rgb(247,251,252); /* Old browsers */
            background: -moz-linear-gradient(top,  rgba(247,251,252,1) 0%, rgba(217,237,242,1) 40%, rgba(173,217,228,1) 100%); /* FF3.6+ */
            background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(247,251,252,1)), color-stop(40%,rgba(217,237,242,1)), color-stop(100%,rgba(173,217,228,1))); /* Chrome,Safari4+ */
            background: -webkit-linear-gradient(top,  rgba(247,251,252,1) 0%,rgba(217,237,242,1) 40%,rgba(173,217,228,1) 100%); /* Chrome10+,Safari5.1+ */
            background: -o-linear-gradient(top,  rgba(247,251,252,1) 0%,rgba(217,237,242,1) 40%,rgba(173,217,228,1) 100%); /* Opera 11.10+ */
            background: -ms-linear-gradient(top,  rgba(247,251,252,1) 0%,rgba(217,237,242,1) 40%,rgba(173,217,228,1) 100%); /* IE10+ */
            background: linear-gradient(to bottom,  rgba(247,251,252,1) 0%,rgba(217,237,242,1) 40%,rgba(173,217,228,1) 100%); /* W3C */
            filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f7fbfc', endColorstr='#add9e4',GradientType=0 ); /* IE6-9 */

            border-radius: 1.25%;
            border-width: 2em;
            font-family: 'Ledger', serif;
            text-align: left;
            padding: 20px;
        }

        h1{
            background-color: #91B7D9;
            color: darkblue;
            text-align: center;
            padding-bottom: 10px;
            border-bottom: 10px;
            font-size: 40pt;
        }

        p{
            font-size: 18pt;
            color: darkblue;
        }

        a{
            font-size: 12pt;
            display: inline;
        }

        /*Tree Data Information*/
        #treeDisc{ font-size: 12pt;}

        #treeDisc b{ text-align: left;}

        #treeDisc a{ text-align: right;}

        #treeDisc table{ margin-bottom: 15px;}

        footer{
            text-align: center;
        }


    </style>

    <!--    Web font for site-->
    <link href='http://fonts.googleapis.com/css?family=Ledger' rel='stylesheet' type='text/css'>

    <title>Plants</title>

</header>

<body>

<center><h1>Tree Types</h1></center>

<p>Welcome to a selection of different trees</p>