<p>Please log in with your username and password</p>
<form action="<?php echo $pageTitle; ?>" method="post">
    <label for="username">Username</label>
    <input type="text" name="username" id="username" maxlength="20" size="20"/><br/>
    <label for="password">Password</label>
    <input type="password" name="password" id="password" maxlength="20" size="20"/><br />
    <input type="submit"/>
</form>